import type { NextPage } from 'next'
import Head from 'next/head'
import ExpandedContent from '../pages/api/expandedContent.tsx'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import Link from 'next/link';


const Home: NextPage = () => {
  const [isNoVicesExpanded, setIsNoVicesExpanded] = useState(false);

  const handleNoVicesToggle = () => {
    setIsNoVicesExpanded(!isNoVicesExpanded);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>puchka</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          puchka
        </h1>

        <p className={styles.description}>
          
          <code className={styles.code}>where dreams come true</code>
        </p>

        <div className={styles.grid}>
        <div
          className={`${styles.card} ${isNoVicesExpanded ? styles.expandedCard : ''}`}
          onClick={handleNoVicesToggle}
        >
          <h2>no vices &rarr;</h2>
          <p>
            Give up on vices and work on your goals, a 30-day challenge
          </p>
          {isNoVicesExpanded && ( <ExpandedContent/>)}
        </div>

          <a className={styles.card}>
            <h2>pakoda &rarr;</h2>
            <p>WIP! creating a bunch of fun games to play in person during a gathering</p>
          </a>

          <Link href="/contact">
            <div className={`${styles.card} ${styles.contactCard}`}>
              <h2>Contact Us &rarr;</h2>
              <p>Get in touch with us for any inquiries or feedback</p>
            </div>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>Made with ❤️ in India</p>
      </footer>
    </div>
  )
}

export default Home
